trigger:
  - main

variables:
  # Azure Resource Manager connection created during pipeline creation
  azureServiceConnectionId: 'YOUR_SERVICE_CONNECTION_ID'
  
  # Web app name
  webAppName: 'YOUR_WEB_APP_NAME'
  
  # Environment name
  environmentName: 'YOUR_WEB_APP_NAME'

  # Project root folder. Point to the directory containing main.py
  projectRoot: $(System.DefaultWorkingDirectory)
  
  # Python version: 3.11 is used to match your render.yaml
  pythonVersion: '3.11'

stages:
  - stage: Build
    displayName: Build stage
    jobs:
      - job: BuildJob
        pool:
          vmImage: ubuntu-latest
        steps:
          - task: UsePythonVersion@0
            inputs:
              versionSpec: '$(pythonVersion)'
            displayName: 'Use Python $(pythonVersion)'
            
          - script: |
              python -m venv antenv
              source antenv/bin/activate
              python -m pip install --upgrade pip
              pip install setup
              pip install -r requirements.txt
            workingDirectory: $(projectRoot)
            displayName: "Install requirements"
            
          - task: ArchiveFiles@2
            displayName: 'Archive files'
            inputs:
              rootFolderOrFile: '$(projectRoot)'
              includeRootFolder: false
              archiveType: zip
              archiveFile: $(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip
              replaceExistingArchive: true

          - upload: $(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip
            displayName: 'Upload package'
            artifact: drop

  - stage: Deploy
    displayName: 'Deploy Web App'
    dependsOn: Build
    condition: succeeded()
    jobs:
      - deployment: DeploymentJob
        pool:
          vmImage: ubuntu-latest
        environment: $(environmentName)
        strategy:
          runOnce:
            deploy:
              steps:
                - task: UsePythonVersion@0
                  inputs:
                    versionSpec: '$(pythonVersion)'
                  displayName: 'Use Python $(pythonVersion)'

                - task: AzureWebApp@1
                  displayName: 'Deploy Azure Web App : $(webAppName)'
                  inputs:
                    azureSubscription: $(azureServiceConnectionId)
                    appName: $(webAppName)
                    package: $(Pipeline.Workspace)/drop/$(Build.BuildId).zip
                    appType: webAppLinux
                    # Oryx will build the app, but since we rely on the zip
                    # App Service runs our startup command automatically.
                    # We can specify 'python main.py' as the explicit start command in the Azure Portal
